name: Build, Test and Package
on:
 # A pull request event will trigger this workflow for main branch
 pull_request:
  branches:
   - main
 push:
  branches: [ main ]
 workflow_dispatch:
jobs:
 build-test-package:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Install dependencies
    run: dotnet restore
  - name: Build ${{ github.repository }}
    run: |
     dotnet build --configuration Release
  - name: Artifactory package creations
   # if: ${{ github.event_name == 'push' }}
    run: |
     export PATH="$PATH:$HOME/.dotnet/tools"
     dotnet pack single-example.csproj -o ./packages
     cd packages
     dotnet nuget push *.nupkg  -s https://shaibz.jfrog.io/artifactory/api/nuget/v3/nuget-local/ -k {{secrets.NUGET_CRED}}
